// CELER BRIDGE ID
export const CELER_BRIDGE_ID = '0x5427fefa';

// HOP L1 BRIDGE ID
export const HOP_L1_BRIDGE_ID = '0x6b7b5fd8';

// HOP L2 BRIDGE ID
export const HOP_L2_BRIDGE_ID = '0x264c837b';

// HYPHEN BRIDGE ID
export const HYPHEN_BRIDGE_ID = '0x2a5c2568';

// MULTICHAIN BRIDGE ID
export const MULTICHAIN_BRIDGE_ID = '0x6b7a8789';

// POLYGON BRIDGE ID
export const POLYGON_BRIDGE_ID = '0x1fdc776a';

// WORMHOLE BRIDGE ID
export const WORMHOLE_BRIDGE_ID = '0x3ee18b22';

// SYNAPSE BRIDGE ID
export const SYNAPSE_BRIDGE_ID = '0x159fd800';
